openapi: 3.0.3
info:
  title: API сервиса платежей
  version: 1.0.0
paths:
  /balance/{username}:
    get:
      operationId: getBalance
      summary: Получить баланс
      tags:
        - balance
      parameters:
        - $ref: '#/components/parameters/Username'
      responses:
        '200':
          $ref: '#/components/responses/SuccessBalance'

  /payment/{username}:
    post:
      operationId: payment
      summary: Вычесть из баланса
      tags:
        - balance
      parameters:
        - $ref: '#/components/parameters/Username'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentValue'
      responses:
        '200':
          $ref: '#/components/responses/SuccessBalance'

components:
  parameters:
    Username:
      name: username
      in: path
      description: Уникальное имя пользователя
      required: true
      schema:
        $ref: '#/components/schemas/Username'

  responses:
    SuccessBalance:
      description: Сумма баланса
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentValue'

  schemas:
    PaymentValue:
      description: Денежное значение
      type: integer
      format: int64
      nullable: false
    Username:
      description: Уникальное имя пользователя
      type: string
      nullable: false