spring:
  application:
    name: payment_service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PAYMENT_AUTH_URI}
springdoc:
  show-actuator: true
  paths-to-match: /, /api/**, /actuator/**
server:
  port: ${PAYMENT_PORT}

balance:
  min: 100
  max: 1_000_000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
        exclude:
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true