<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.ya.practicum</groupId>
        <artifactId>my-market-app</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>payment_api</artifactId>
    <version>${payment_api.version}</version>
    <packaging>jar</packaging>

    <name>payment_api</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <!-- Генерация для сервера (Spring) -->
                    <execution>
                        <id>generate-payment-service</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/api-spec.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <invokerPackage>ru.ya.practicum.payment</invokerPackage>
                            <apiPackage>ru.ya.practicum.payment.api</apiPackage>
                            <modelPackage>ru.ya.practicum.payment.model</modelPackage>
                            <addCompileSourceRoot>true</addCompileSourceRoot>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <reactive>true</reactive>
                                <openApiNullable>false</openApiNullable>
                                <generateClientAsBean>false</generateClientAsBean>
                                <generateApiTests>false</generateApiTests>
                                <generateModelTests>false</generateModelTests>
                                <generateApiDocumentation>false</generateApiDocumentation>
                                <generateModelDocumentation>false</generateModelDocumentation>

                                <interfaceOnly>true</interfaceOnly>
                                <useTags>true</useTags>
                                <openApiNullable>false</openApiNullable>
                                <sourceFolder>src/main/java</sourceFolder>

                                <useSpringBoot3>true</useSpringBoot3>
                                <serializableModel>true</serializableModel>
                                <dateLibrary>java8</dateLibrary>
                                <java8>true</java8>

                                <skipGenerateTests>true</skipGenerateTests>
                            </configOptions>
                        </configuration>
                    </execution>

                    <!-- Генерация для клиента (WebClient) -->
                    <execution>
                        <id>generate-payment-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/api-spec.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>webclient</library>
                            <output>${project.build.directory}/generated-sources/payment-client</output>
                            <invokerPackage>ru.ya.practicum.payment.client</invokerPackage>
                            <apiPackage>ru.ya.practicum.payment.client.api</apiPackage>
                            <modelPackage>ru.ya.practicum.payment.client.model</modelPackage>
                            <addCompileSourceRoot>true</addCompileSourceRoot>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <reactive>true</reactive>
                                <openApiNullable>false</openApiNullable>
                                <generateClientAsBean>false</generateClientAsBean>
                                <generateApiTests>false</generateApiTests>
                                <generateModelTests>false</generateModelTests>
                                <generateApiDocumentation>false</generateApiDocumentation>
                                <generateModelDocumentation>false</generateModelDocumentation>


                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-generated-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/openapi/src/main/java</source>
                                <source>${project.build.directory}/generated-sources/payment-client/src/main/java
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
