/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.ya.practicum.payment.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-18T11:57:12.454995+03:00[Europe/Moscow]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "balance", description = "the balance API")
public interface BalanceApi {

    String PATH_GET_BALANCE = "/balance/{sessionId}";
    /**
     * GET /balance/{sessionId} : Получить баланс
     *
     * @param sessionId Идентификатор сессии (required)
     * @return Сумма баланса (status code 200)
     */
    @Operation(
        operationId = "getBalance",
        summary = "Получить баланс",
        tags = { "balance" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Сумма баланса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Long.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BalanceApi.PATH_GET_BALANCE,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Long>> getBalance(
        @NotNull @Parameter(name = "sessionId", description = "Идентификатор сессии", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") String sessionId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        return result.then(Mono.empty());

    }


    String PATH_PAYMENT = "/payment/{sessionId}";
    /**
     * POST /payment/{sessionId} : Вычесть из баланса
     *
     * @param sessionId Идентификатор сессии (required)
     * @param body  (optional)
     * @return Сумма баланса (status code 200)
     */
    @Operation(
        operationId = "payment",
        summary = "Вычесть из баланса",
        tags = { "balance" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Сумма баланса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Long.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = BalanceApi.PATH_PAYMENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<Long>> payment(
        @NotNull @Parameter(name = "sessionId", description = "Идентификатор сессии", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") String sessionId,
        @Parameter(name = "body", description = "") @Valid @RequestBody(required = false) Mono<Long> body,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        return result.then(body).then(Mono.empty());

    }

}
